removed AJDT
ERROR: org.eclipse.equinox.p2.director code=10053 Cannot complete the
install because one or more required items could not be found.
  at
org.eclipse.oomph.util.OomphPlugin.coreException(OomphPlugin.java:280)
  at
org.eclipse.oomph.p2.internal.core.ProfileTransactionImpl.resolve(ProfileTransactionImpl.java:425)
  at
org.eclipse.oomph.p2.internal.core.ProfileTransactionImpl.commit(ProfileTransactionImpl.java:337)
  at
org.eclipse.oomph.setup.p2.impl.P2TaskImpl.perform(P2TaskImpl.java:729)
  at
org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.doPerformNeededSetupTasks(SetupTaskPerformer.java:3324)
  at
org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performNeededSetupTasks(SetupTaskPerformer.java:3252)
  at
org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performTriggeredSetupTasks(SetupTaskPerformer.java:3233)
  at
org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.perform(SetupTaskPerformer.java:3133)
  at
org.eclipse.oomph.setup.ui.wizards.ProgressPage$9.run(ProgressPage.java:567)
  at
org.eclipse.oomph.setup.ui.wizards.ProgressPage$11$1.run(ProgressPage.java:693)
  at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
  ERROR: org.eclipse.equinox.p2.director code=0 Software being
installed: artificial_root 1.0.0.v1496843813046
  ERROR: org.eclipse.equinox.p2.director code=0 Missing requirement: JDT
Weaving 2.2.4.201512160910 (org.eclipse.contribution.weaving.jdt
2.2.4.201512160910) requires 'bundle org.eclipse.ui.browser
[3.4.0,3.6.0)' but it could not be found
  ERROR: org.eclipse.equinox.p2.director code=1 Cannot satisfy
dependency:
    ERROR: org.eclipse.equinox.p2.director code=0 From: artificial_root
1.0.0.v1496843813046
    ERROR: org.eclipse.equinox.p2.director code=0 To:
org.eclipse.ajdt.feature.group [2.2.4.201512160910]
  ERROR: org.eclipse.equinox.p2.director code=1 Cannot satisfy
dependency:
    ERROR: org.eclipse.equinox.p2.director code=0 From: AspectJ
Development Tools 2.2.4.201512160910 (org.eclipse.ajdt.feature.group
2.2.4.201512160910)
    ERROR: org.eclipse.equinox.p2.director code=0 To:
org.eclipse.contribution.weaving.jdt 0.0.0